import fs from "node:fs";
import {
  fileExists,
  projectPath,
  readJsonFile,
  readProjectConfig,
  writeJsonFile,
} from "@/lib/project";
import { loadStore } from "@/lib/knowledge/store";

export type ThinPitchResult = {
  ok: boolean;
  artifacts: string[];
  qualityScore: number;
  recommendationCount: number;
  withEvidence: number;
  message: string;
};

/**
 * Sprint 3 thin pitch adapter — executive package citing graph evidence.
 */
export function generateThinPitch(slug: string): ThinPitchResult {
  const config = readProjectConfig(slug);
  const store = loadStore();
  const recs = [...store.entities.values()].filter(
    (e) =>
      e.sourceProjects.includes(slug) && e.epistemicClass === "recommendation",
  );
  const withEvidence = recs.filter((r) => r.evidenceIds.length > 0);
  const maturity = readJsonFile<{ overallScore?: number }>(
    projectPath(slug, "analysis/digital-maturity.json"),
  );
  const confidence = fileExists(slug, "reports/confidence-report.md");

  const packageJson = {
    schemaVersion: "1.0.0",
    kind: "thin_pitch",
    projectSlug: slug,
    company: config.name,
    industry: config.industry,
    websiteUrl: config.websiteUrl,
    generatedAt: new Date().toISOString(),
    digitalMaturityScore: maturity?.overallScore ?? null,
    recommendations: recs.map((r) => ({
      id: r.id,
      name: r.name,
      summary:
        typeof r.properties.description === "string"
          ? r.properties.description
          : r.name,
      evidenceIds: r.evidenceIds,
      confidence: r.epistemicClass,
    })),
    confidenceCap: 0.7,
    notes:
      "Thin runtime pitch package for Sprint 3. Sufficient for gates and demo; not polished sales collateral.",
  };

  writeJsonFile(projectPath(slug, "reports/pitch/package.json"), packageJson);

  const md = `# Executive pitch — ${config.name}

Generated: ${packageJson.generatedAt}
Kind: thin (Sprint 3 runtime)

## Objective

Consulting-quality digital transformation assessment, interactive prototype, and executive pitch for **${config.industry}**.

## Snapshot

- Website: ${config.websiteUrl}
- Digital maturity score: ${maturity?.overallScore ?? "n/a"}
- Recommendations: ${recs.length} (${withEvidence.length} with evidence)
- Confidence report present: ${confidence ? "yes" : "no"}

## Recommendations (evidence-linked)

${recs
  .map(
    (r) =>
      `### ${r.name}\n\n${
        typeof r.properties.description === "string"
          ? r.properties.description
          : r.name
      }\n\nEvidence: ${
        r.evidenceIds.length
          ? r.evidenceIds.map((id) => `\`${id}\``).join(", ")
          : "_none_"
      }\n`,
  )
  .join("\n") || "_No recommendation entities in knowledge graph_"}

## Prototype surfaces

See \`prototype/manifest.json\` for thin prototype routes.

## Disclaimer

Demonstration package generated by Forge Core Runtime. Not a substitute for a final client-facing pitch deck.
`;

  fs.mkdirSync(projectPath(slug, "reports/pitch"), { recursive: true });
  fs.writeFileSync(projectPath(slug, "reports/pitch/executive-pitch.md"), md, "utf8");

  const coverage = recs.length ? withEvidence.length / recs.length : 1;
  const ok = coverage >= 0.8 || recs.length === 0;

  return {
    ok,
    artifacts: [
      "reports/pitch/package.json",
      "reports/pitch/executive-pitch.md",
    ],
    qualityScore: Math.min(0.7, 0.4 + coverage * 0.3),
    recommendationCount: recs.length,
    withEvidence: withEvidence.length,
    message: ok
      ? "Thin pitch package written"
      : "Pitch written but evidence coverage below threshold",
  };
}
